org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true

mod_id=randomizer
mod_version=0.10
mod_group=com.ghzdude.randomizer

minecraft_version=26.2
forge_version=65.1.3